services:
    ytdlp_web_player:
        # build: .
        image: matszwe02/ytdlp_web_player:stable
        # volumes:
        #     - ./src/cookies.txt:/app/cookies.txt
        #     - ./yt-dlp-plugins:/root/.config/yt-dlp/plugins:ro
        restart: unless-stopped
        # env_file:
        #     - src/.env
        ports:
            - 5000:5000



################################################################################
#     # Uncomment this section to enable daily updates.
#     watchtower:
#         image: nickfedor/watchtower
#         volumes:
#             - /var/run/docker.sock:/var/run/docker.sock
################################################################################



################################################################################
#     # Uncomment this section to open HTTPS under port 5001
#     nginx:
#         image: valian/docker-nginx-auto-ssl
#         restart: on-failure
#         ports:
#             - 5001:443
#         volumes:
#             - ./.ssl:/etc/resty-auto-ssl
#         environment:
#             ALLOWED_DOMAINS: 'localhost'
#             SITES: 'localhost=ytdlp_web_player:5000'
################################################################################